#+hugo_base_dir: ../


* Website
** Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :author false :toc false
:END:
#+LANGUAGE: en
#+OPTIONS: ':t

*** Welcome!
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

I'm **John Lalor**. 
I am an Assistant Professor at the [[https://mendoza.nd.edu][Mendoza College of Business]] at the [[https://www.nd.edu][University of Notre Dame]]. 
I completed my Ph.D. at the University of Massachusetts Amherst in the [[https://cics.umass.edu][College of Information and Computer Science]]. 
At UMass I was a member of the Bio-NLP group, working with Dr. Hong Yu. 
My research interests are in Machine Learning and Natural Language Processing. 
I am particularly interested in model evaluation, quantifying uncertainty, and biomedical informatics.

Prior to UMass, I worked as a software developer at Eze Software in Chicago and as an IT Audit Associate for KPMG. 
I received my Master's Degree in Computer Science at DePaul University, where I worked on projects in Computer Science Education and Recommender Systems. 



**** Recent Updates


- *January 2023*: /Evaluating the Efficacy of NoteAid on EHR Note Comprehension among US Veterans through Amazon Mechanical Turk/ accepted at the International Journal of Medical Informatics.
- *January 2023*: /Business Analytics in Healthcare: Past, Present, and Future Trends/ accepted at Manufacturing and Service Operations Management.
- *September 2022*: /py-irt: A Scalable Item Response Theory Library for Python/ accepted at the INFORMS Journal on Computing.


* TODO My first post                                        :tag1:@category1:
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
This is my post body!
