#+TITLE: Personal Website
#+DATE: May 4th, 2023
#+AUTHOR: John P. Lalor
#+hugo_base_dir: ../


* Website
** Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc false :author false
:EXPORT_OPTIONS: author:nil 
:END:
#+LANGUAGE: en
#+OPTIONS: ':t

*** Welcome!
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

I'm **John Lalor**. 
I am an Assistant Professor at the [[https://mendoza.nd.edu][Mendoza College of Business]] at the [[https://www.nd.edu][University of Notre Dame]]. 
I completed my Ph.D. at the University of Massachusetts Amherst in the [[https://cics.umass.edu][College of Information and Computer Science]]. 
At UMass I was a member of the Bio-NLP group, working with Dr. Hong Yu. 
My research interests are in Machine Learning and Natural Language Processing. 
I am particularly interested in model evaluation, quantifying uncertainty, and biomedical informatics.

Prior to UMass, I worked as a software developer at Eze Software in Chicago and as an IT Audit Associate for KPMG. 
I received my Master's Degree in Computer Science at DePaul University, where I worked on projects in Computer Science Education and Recommender Systems. 

**** Recent Updates

- *January 2023*: /Evaluating the Efficacy of NoteAid on EHR Note Comprehension among US Veterans through Amazon Mechanical Turk/ accepted at the International Journal of Medical Informatics.
- *January 2023*: /Business Analytics in Healthcare: Past, Present, and Future Trends/ accepted at Manufacturing and Service Operations Management.
- *September 2022*: /py-irt: A Scalable Item Response Theory Library for Python/ accepted at the INFORMS Journal on Computing.

*** Research
:PROPERTIES:
:EXPORT_FILE_NAME: research
:EXPORT_HUGO_WEIGHT: -100
:EXPORT_HUGO_MENU: :menu main
:END:

**** Journal Articles

- J.P. Lalor, H. Wu, K. Mazor. H. Yu. Evaluating the Efficacy of NoteAid on EHR Note Comprehension among US Veterans through Amazon Mechanical Turk. International Journal of Medical Informatics. *Forthcoming*.
- K.D. Wowak, J.P. Lalor, S. Somanchi, C. Angst. Business Analytics in Healthcare: Past, Present, and Future Trends. Manufacturing and Service Operations Management. *Forthcoming.*
- J.P. Lalor, P. Rodriguez. py-irt: A Scalable Item Response Theory Library for Python. *INFORMS Journal on Computing.* 2022. doi:10.1287/ijoc.2022.1250
- J.P. Lalor, W. Hu, M. Tran, H. Wu, K. Mazor, H. Yu. Evaluating the Effectiveness of NoteAid in a Community Hospital Setting: Randomized Control Trial. *J Med Internet Res* 2021;23(5):e26354 
- J. Chen, J.P. Lalor, W. Liu, E. Druhl, E. Granillo, V. Vimalananda, H. Yu. Detecting Hypoglycemia Incidents Reported in Patients Secure Messages: Using Cost-sensitive Learning and Oversampling to Reduce Data Imbalance. *J Med Internet Res* 2019;21(3):e11990. doi:10.2196/11990. 
- J.P. Lalor, B. Woolf, H. Yu. Improving EHR Note Comprehension with NoteAid: A Randomized Trial of EHR Note Comprehension Interventions with Crowdsourced Workers, *J Med Internet Res* 2019;21(1):e10793.
- J.P. Lalor, H. Wu, L. Chen, K. Mazor, H. Yu. ComprehENotes, an Instrument for Assessing Patient Electronic Health Record Note Reading Comprehension: Development and Validation, *J Med Internet Res* 2018;20(4):e139.


**** Conference Publications

- J. P. Lalor, Y. Yang, K. Smith, N. Forsgren, A. Abbasi. Benchmarking Intersectional Biases in NLP. *NAACL 2022.*
- A. Abbasi, D. Dobolyi, J. P. Lalor, R. Netemeyer, K. Smith, and Y. Yang. Constructing a Psychometric Testbed for Fair Natural Language Processing. *EMNLP 2021.* 
    - *Authors listed alphabetically*
- H. Safadi, J.P. Lalor, N. Berente. The Effect of Bots on Human Interaction in Online Communities. *ICIS 2021.*
    - *Best Theory Paper*
- N. Berente, J.P. Lalor, S. Somanchi, A. Abbasi. The Illusion of Certainty and Data-Driven Decision Making in Emergent Situations. *ICIS 2021.*
- P. Rodriguez, J. Barrow, A.M. Hoyle, J.P. Lalor, R. Jia and J. Boyd-Graber. Rethinking NLP Leaderboards with Methods from Educational Testing. *ACL 2021.* 
- J.P. Lalor, H. Yu. Dynamic Data Selection for Curriculum Learning via Ability Estimation. *Findings of ACL: EMNLP 2020.* 
- J.P. Lalor, H. Wu, H. Yu. Learning Latent Parameters without Human Response Patterns: Item Response Theory with Artificial Crowds. *EMNLP 2019.* 
- J.P. Lalor, H. Wu, T. Munkhdalai, H. Yu. Understanding Deep Learning Performance through an Examination of Test Set Difficulty: A Psychometric Case Study. In *EMNLP 2018.* 
- J.P. Lalor, H. Wu, H. Yu. Building an Evaluation Scale using Item Response Theory, In *EMNLP 2016*.
- C. Miller, A. Settle, and J.P. Lalor. Learning Object-Oriented Programming in Python: Towards an Inventory of Difficulties and Testing Pitfalls, *SIGITE 2015.*
- A. Settle, J.P. Lalor, and T. Steinbach. Evaluating a Linked-courses Learning Community for Development Majors. In *SIGITE 2015.*
- A. Settle, J.P. Lalor, and T. Steinbach. A Computer Science Linked-courses Learning Community, In *ITiCSE 2015.* 
- A. Settle, J.P. Lalor, and T. Steinbach. Reconsidering the Impact of CS1 on Novice Attitudes. In *SIGCSE 2015.*


**** Workshop Presentations, Posters, and Abstracts

- M. Ma, J.P. Lalor. An Empirical Analysis of Human-Bot Interaction on Reddit. *Workshop on Noisy User-generated Text (W-NUT),* 2020. 
- J.P. Lalor, H. Guo. Towards Measuring Algorithmic Interpretability. *INFORMS Workshop on Data Science,* 2020.
- E. Cho, H. Xie, J.P. Lalor, V. Kumar, W.M. Campbell. Efficient Semi-Supervised Learning for Natural Language Understanding by Optimizing Diversity. *ASRU 2019* 
- J.P. Lalor, H. Wu, H. Yu. Learning Latent Parameters without Human Response Patterns: Item Response Theory with Artificial Crowds. *NAACL Workshop on Shortcomings in Vision and Language (SiVL)* 2019 
- J.P. Lalor, H. Wu, H. Yu. Comparing Human and DNN-Ensemble Response Patterns for Item Response Theory Model Fitting. *NAACL Workshop on Cognitive Modeling and Computational Linguistics (CMCL)* 2019 
- J.P. Lalor, H. Wu, H. Yu. Soft Label Memorization-Generalization for Natural Language Inference. *UAI Workshop on Uncertainty in Deep Learning.*, 2018. 
- J. Chen, J.P. Lalor, H. Yu. Detecting Hypoglycemia Incidents from Patients' Secure Messages. *American Medical Informatics Association (AMIA) Annual Symposium* Poster, 2018
- J.P. Lalor, H. Wu, H. Yu, Modeling Difficulty to Understand Deep Learning Performance. *Northern Lights Deep Learning Workshop (NLDL), 2018* 
- J.P. Lalor, H. Wu, L. Chen, K. Mazor, H. Yu, Generating a Test of Electronic Health Narrative Comprehension with Item Response Theory. *American Medical Informatics Association (AMIA) Annual Symposium* Podium Abstract, 2017. 
- J.P. Lalor, H. Wu, H. Yu. CIFT: Crowd-Informed Fine-Tuning to Improve Machine Learning Ability, *HCOMP 2017 Works in Progress* 
- T. Munkhdalai, J.P. Lalor, H. Yu. Citation Analysis with Neural Attention Models, In *LOUHI 2016 EMNLP Workshop*. 

*** Teaching
:PROPERTIES:
:EXPORT_FILE_NAME: teaching
:EXPORT_HUGO_WEIGHT: -50
:EXPORT_HUGO_MENU: :menu main
:END:

**** University of Notre Dame

- ITAO 80810: Machine Learning and NLP
- MSSA 60230: Data Analysis with Python
- ITAO 40250: Unstructured Data Analytics
- ITAO 70810: Data Wrangling with R 
- ITAO 70800: Integrated Analytics Deep Dive

**** University of Massachusetts Amherst

- UMass First Year Seminar: Artificial Intelligence and Healthcare
*** Notre Dame Business Analytics, Learning, and Language Lab
:PROPERTIES:
:EXPORT_FILE_NAME: ball
:EXPORT_HUGO_WEIGHT: 0
:EXPORT_HUGO_MENU: :menu main :name ND-BALL
:END:


I lead the Notre Dame Business Analytics, Learning, and Language Lab (ND-BALL).
Code from the lab is available on [[https://github.com/nd-ball][GitHub]].

**** Current Students

- Katie Ryan (MS, Business Analytics)
- Sandy Huang (MS, Business Analytics)

**** Former Students 

- Vincent Buono (BBA, Business Analytics)
- Michael Ma (MS, Business Analytics)
- Aiden McFadden (BBA, Business Analytics)
- Keegan McLaughlin (BBA, Business Analytics)

** Blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc false :type post
:END:
#+LANGUAGE: en
#+OPTIONS: ':t


* TODO My first post                                        :tag1:@category1:
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
This is my post body!
